/**
 * RegLayer — Prisma Configuration
 *
 * WHY: Multi-schema Prisma setup requires explicit configuration beyond schema.prisma.
 * WHAT: Configures Prisma client generation: output directory, preview features, datasource.
 * HOW: Points to generated/prisma output. Enables driverAdapters preview feature for PrismaPg.
 */
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
