"use client";

/**
 * RegLayer — AI Quality Gate Badge
 *
 * Shows pass/fail indicators on code blocks generated by the AI.
 * Validates: accessibility attributes, semantic HTML, ARIA patterns.
 *
 * WHY: Before users copy AI-generated code, they should know if it meets
 *      the workspace's accessibility standards.
 *
 * INSPIRED BY: GitHub Copilot code review badges, ESLint inline markers
 */

import { useState, useCallback } from "react";
import { Shield, CheckCircle2, AlertTriangle, ChevronDown, ChevronUp } from "lucide-react";

interface QualityCheck {
  name: string;
  passed: boolean;
  message: string;
  severity: "error" | "warning" | "info";
}

interface CodeQualityGateProps {
  code: string;
  language?: string;
}

// Lightweight client-side accessibility checks for generated HTML/JSX
function runAccessibilityChecks(code: string, language?: string): QualityCheck[] {
  const checks: QualityCheck[] = [];
  const isHTML = language === "html" || language === "jsx" || language === "tsx" || code.includes("<");

  if (!isHTML) return checks;

  // Check: Images have alt attributes
  const imgWithoutAlt = code.match(/<img(?![^>]*alt=)[^>]*>/g);
  checks.push({
    name: "Image alt text",
    passed: !imgWithoutAlt,
    message: imgWithoutAlt ? `${imgWithoutAlt.length} image(s) missing alt attribute` : "All images have alt text",
    severity: imgWithoutAlt ? "error" : "info",
  });

  // Check: Buttons have accessible names
  const emptyButtons = code.match(/<button[^>]*>\s*<(?:svg|img|icon)/gi);
  checks.push({
    name: "Button labels",
    passed: !emptyButtons,
    message: emptyButtons ? "Icon-only button(s) may need aria-label" : "Buttons have accessible names",
    severity: emptyButtons ? "warning" : "info",
  });

  // Check: Form inputs have labels
  const inputsWithoutLabel = code.match(/<input(?![^>]*aria-label)[^>]*>/g);
  const hasLabels = code.includes("<label") || code.includes("aria-label") || code.includes("aria-labelledby");
  checks.push({
    name: "Form labels",
    passed: !inputsWithoutLabel || hasLabels,
    message: inputsWithoutLabel && !hasLabels ? "Input(s) may need associated labels" : "Form inputs have labels",
    severity: inputsWithoutLabel && !hasLabels ? "warning" : "info",
  });

  // Check: No divs used as buttons
  const divButtons = code.match(/<div[^>]*onClick/g);
  checks.push({
    name: "Semantic elements",
    passed: !divButtons,
    message: divButtons ? "Use <button> instead of <div onClick>" : "Using semantic HTML elements",
    severity: divButtons ? "error" : "info",
  });

  // Check: ARIA roles used correctly
  const hasRole = code.includes('role="');
  const hasAriaHidden = code.includes('aria-hidden="true"');
  if (hasRole || hasAriaHidden) {
    checks.push({
      name: "ARIA usage",
      passed: true,
      message: "ARIA attributes present",
      severity: "info",
    });
  }

  // Check: Color contrast (basic — detects hardcoded light colors on white bg)
  const lightColors = code.match(/#(?:f[0-9a-f]{5}|e[0-9a-f]{5}|d[0-9a-f]{5})/gi);
  if (lightColors && lightColors.length > 0) {
    checks.push({
      name: "Color contrast",
      passed: false,
      message: "Light color values detected — verify contrast ratio meets 4.5:1",
      severity: "warning",
    });
  }

  // Check: Focus management
  const hasFocusHandling = code.includes("tabIndex") || code.includes("tabindex") || code.includes("onKeyDown") || code.includes("onkeydown");
  if (code.includes("onClick") || code.includes("onclick")) {
    checks.push({
      name: "Keyboard access",
      passed: hasFocusHandling,
      message: hasFocusHandling ? "Keyboard event handling present" : "Click handler without keyboard equivalent",
      severity: hasFocusHandling ? "info" : "warning",
    });
  }

  return checks;
}

export function CodeQualityGate({ code, language }: CodeQualityGateProps) {
  const [checks, setChecks] = useState<QualityCheck[] | null>(null);
  const [expanded, setExpanded] = useState(false);

  const runChecks = useCallback(() => {
    const results = runAccessibilityChecks(code, language);
    setChecks(results);
    setExpanded(results.some((c) => !c.passed));
  }, [code, language]);

  // Auto-run on mount if it looks like HTML/JSX
  if (checks === null && (language === "html" || language === "jsx" || language === "tsx" || code.includes("<"))) {
    runChecks();
  }

  if (!checks || checks.length === 0) return null;

  const passed = checks.filter((c) => c.passed).length;
  const total = checks.length;
  const allPassed = passed === total;
  const hasErrors = checks.some((c) => c.severity === "error" && !c.passed);

  return (
    <div className={`mt-1.5 rounded-md border text-xs ${
      allPassed
        ? "border-green-200 dark:border-green-800 bg-green-50 dark:bg-green-950/20"
        : hasErrors
          ? "border-red-200 dark:border-red-800 bg-red-50 dark:bg-red-950/20"
          : "border-amber-200 dark:border-amber-800 bg-amber-50 dark:bg-amber-950/20"
    }`}>
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center gap-2 px-2.5 py-1.5"
      >
        <Shield className={`h-3 w-3 ${allPassed ? "text-green-500" : hasErrors ? "text-red-500" : "text-amber-500"}`} />
        <span className={`font-medium ${allPassed ? "text-green-700 dark:text-green-400" : hasErrors ? "text-red-700 dark:text-red-400" : "text-amber-700 dark:text-amber-400"}`}>
          A11y: {passed}/{total} checks passed
        </span>
        <span className="ml-auto">
          {expanded ? <ChevronUp className="h-3 w-3" /> : <ChevronDown className="h-3 w-3" />}
        </span>
      </button>

      {expanded && (
        <div className="px-2.5 pb-2 space-y-1 border-t border-neutral-200 dark:border-neutral-700 pt-1.5">
          {checks.map((check, i) => (
            <div key={i} className="flex items-center gap-1.5">
              {check.passed ? (
                <CheckCircle2 className="h-3 w-3 text-green-500 shrink-0" />
              ) : (
                <AlertTriangle className={`h-3 w-3 shrink-0 ${check.severity === "error" ? "text-red-500" : "text-amber-500"}`} />
              )}
              <span className="text-[11px] text-neutral-700 dark:text-neutral-300">{check.message}</span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
