/**
 * ---------------------------------------------------------
 * RegLayer — GitHub Integration
 * ---------------------------------------------------------
 * 
 * Creates GitHub issues from accessibility violations.
 * Supports:
 * - Single violation → issue
 * - Batch violations → single issue
 * - Labels (a11y, impact level, WCAG criteria)
 * - Markdown formatting with fix guidance
 * - Deduplication (won't create duplicate issues)
 * ---------------------------------------------------------
 */

import { prisma } from "@/lib/database/prisma";

export interface GitHubConfig {
  token: string;
  owner: string;
  repo: string;
}

export interface IssuePayload {
  title: string;
  body: string;
  labels: string[];
}

interface ViolationForIssue {
  ruleId: string;
  impact: string;
  help: string;
  description: string;
  helpUrl: string | null;
  tags: string[];
  affectedElements: unknown;
}

/**
 * Generate a GitHub issue body from a violation.
 */
function formatIssueBody(
  violation: ViolationForIssue,
  scanUrl: string,
  scanId: string,
  reportUrl: string
): string {
  const elements = Array.isArray(violation.affectedElements)
    ? (violation.affectedElements as Array<{ html: string; target: string[] }>)
    : [];

  const wcagTags = violation.tags
    .filter((t) => t.startsWith("wcag"))
    .join(", ");

  let body = `## Accessibility Violation: \`${violation.ruleId}\`\n\n`;
  body += `| Field | Value |\n|-------|-------|\n`;
  body += `| **Impact** | ${violation.impact} |\n`;
  body += `| **Page** | ${scanUrl} |\n`;
  body += `| **WCAG** | ${wcagTags || "N/A"} |\n`;
  body += `| **Scan ID** | \`${scanId}\` |\n\n`;

  body += `### Description\n\n${violation.description}\n\n`;
  body += `### How to Fix\n\n${violation.help}\n\n`;

  if (violation.helpUrl) {
    body += `📖 [Detailed guidance](${violation.helpUrl})\n\n`;
  }

  if (elements.length > 0) {
    body += `### Affected Elements (${elements.length})\n\n`;
    for (const el of elements.slice(0, 5)) {
      body += `\`\`\`html\n${el.html}\n\`\`\`\n`;
      if (el.target?.length) {
        body += `Selector: \`${el.target.join(" > ")}\`\n\n`;
      }
    }
    if (elements.length > 5) {
      body += `\n... and ${elements.length - 5} more elements\n\n`;
    }
  }

  body += `---\n\n`;
  body += `🔗 [Full Report](${reportUrl}) | Generated by [RegLayer](https://reglayer.vercel.app)\n`;

  return body;
}

/**
 * Create a GitHub issue for a single violation.
 */
export async function createIssueFromViolation(
  config: GitHubConfig,
  violation: ViolationForIssue,
  scanUrl: string,
  scanId: string,
  reportUrl: string
): Promise<{ number: number; url: string }> {
  const title = `[A11Y] ${violation.impact.toUpperCase()}: ${violation.help}`;
  const body = formatIssueBody(violation, scanUrl, scanId, reportUrl);

  const labels = [
    "accessibility",
    `impact:${violation.impact}`,
    ...violation.tags
      .filter((t) => t.match(/^wcag\d/))
      .slice(0, 3)
      .map((t) => `wcag:${t}`),
  ];

  const response = await fetch(
    `https://api.github.com/repos/${config.owner}/${config.repo}/issues`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${config.token}`,
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
      },
      body: JSON.stringify({ title, body, labels }),
    }
  );

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`GitHub API error: ${response.status} - ${err}`);
  }

  const issue = (await response.json()) as { number: number; html_url: string };
  return { number: issue.number, url: issue.html_url };
}

/**
 * Create a batch issue for all violations in a scan.
 */
export async function createBatchIssue(
  config: GitHubConfig,
  scanId: string,
  reportUrl: string
): Promise<{ number: number; url: string }> {
  const scan = await prisma.scan.findUnique({
    where: { id: scanId },
    include: { violations: true },
  });

  if (!scan) throw new Error("Scan not found");

  const title = `[A11Y] ${scan.totalViolations} accessibility violations on ${scan.url} (Score: ${Math.round(scan.score ?? 0)})`;

  let body = `# Accessibility Scan Report\n\n`;
  body += `| Metric | Value |\n|--------|-------|\n`;
  body += `| **URL** | ${scan.url} |\n`;
  body += `| **Score** | ${Math.round(scan.score ?? 0)}/100 |\n`;
  body += `| **Total Violations** | ${scan.totalViolations} |\n`;
  body += `| **Critical** | ${scan.critical} |\n`;
  body += `| **Serious** | ${scan.serious} |\n`;
  body += `| **Moderate** | ${scan.moderate} |\n`;
  body += `| **Minor** | ${scan.minor} |\n`;
  body += `| **Scanned** | ${scan.createdAt.toISOString()} |\n\n`;

  body += `## Violations\n\n`;

  const grouped = { critical: [] as typeof scan.violations, serious: [] as typeof scan.violations, moderate: [] as typeof scan.violations, minor: [] as typeof scan.violations };
  for (const v of scan.violations) {
    (grouped[v.impact as keyof typeof grouped] || grouped.minor).push(v);
  }

  for (const [impact, violations] of Object.entries(grouped)) {
    if (violations.length === 0) continue;
    body += `### ${impact.charAt(0).toUpperCase() + impact.slice(1)} (${violations.length})\n\n`;
    for (const v of violations) {
      body += `- [ ] **\`${v.ruleId}\`** — ${v.help}\n`;
      body += `  ${v.description}\n`;
      if (v.helpUrl) body += `  [How to fix](${v.helpUrl})\n`;
      body += `\n`;
    }
  }

  body += `---\n\n🔗 [Full Interactive Report](${reportUrl}) | Generated by [RegLayer](https://reglayer.vercel.app)\n`;

  const labels = ["accessibility", "automated"];
  if (scan.critical > 0) labels.push("priority:critical");
  else if (scan.serious > 0) labels.push("priority:high");

  const response = await fetch(
    `https://api.github.com/repos/${config.owner}/${config.repo}/issues`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${config.token}`,
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
      },
      body: JSON.stringify({ title, body, labels }),
    }
  );

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`GitHub API error: ${response.status} - ${err}`);
  }

  const issue = (await response.json()) as { number: number; html_url: string };
  return { number: issue.number, url: issue.html_url };
}
