import { readFile } from "node:fs/promises";
import prismaSdk from "@prisma/internals";
import { type Client, escapeIdentifier, escapeLiteral } from "pg";

export async function createCrawlSchema(client: Client, modelNames = ["CrawlJobRecord"]) {
  const { datamodel } = await prismaSdk.getDMMF({
    datamodel: await readFile(new URL("../../prisma/schema.prisma", import.meta.url), "utf8"),
  });
  const types: Record<string, string> = {
    String: "TEXT", Int: "INTEGER", BigInt: "BIGINT", Float: "DOUBLE PRECISION", Boolean: "BOOLEAN", DateTime: "TIMESTAMP(3)", Json: "JSONB",
  };
  for (const name of modelNames) {
    const model = datamodel.models.find(candidate => candidate.name === name);
    if (!model) throw new Error(`Missing ${name} metadata`);
    const columns: string[] = [];
    for (const field of model.fields) {
      if (field.kind === "object") continue;
      if (name === "Violation" && field.name === "embedding" && field.kind === "unsupported" && !field.isRequired) continue;
      if (field.nativeType && !["Text", "VarChar", "Timestamp"].includes(field.nativeType[0]) || !["scalar", "enum"].includes(field.kind)) throw new Error(`Unsupported fixture field ${name}.${field.name}`);
      let type = types[field.type];
      if (field.kind === "enum") {
        const definition = datamodel.enums.find(candidate => candidate.name === field.type);
        if (!definition) throw new Error(`Missing enum ${field.type}`);
        try {
          await client.query(`CREATE TYPE ${escapeIdentifier(field.type)} AS ENUM (${definition.values.map(value => escapeLiteral(value.name)).join(", ")})`);
        } catch (error) {
          if ((error as { code?: string }).code !== "42710") throw error;
        }
        type = escapeIdentifier(field.type);
      }
      if (!type) throw new Error(`Unsupported fixture type ${field.type}`);
      let defaultClause = "";
      if (field.hasDefaultValue) {
        if (field.isList && Array.isArray(field.default)) defaultClause = ` DEFAULT ARRAY[${field.default.map(value => escapeLiteral(String(value))).join(", ")}]::${type}[]`;
        else if (typeof field.default === "string") defaultClause = ` DEFAULT ${escapeLiteral(field.default)}`;
        else if (typeof field.default === "number" || typeof field.default === "boolean") defaultClause = ` DEFAULT ${field.default}`;
        else if (typeof field.default === "object" && field.default && "name" in field.default) {
          if (field.default.name === "now") defaultClause = " DEFAULT CURRENT_TIMESTAMP";
          else if (field.default.name === "autoincrement") defaultClause = " GENERATED BY DEFAULT AS IDENTITY";
          else if (field.default.name !== "cuid") throw new Error(`Unsupported fixture default ${field.default.name}`);
        } else throw new Error(`Unsupported fixture default for ${field.name}`);
      }
      columns.push(`${escapeIdentifier(field.dbName ?? field.name)} ${type}${field.isList ? "[]" : ""}${field.isRequired ? " NOT NULL" : ""}${field.isId ? " PRIMARY KEY" : ""}${defaultClause}`);
    }
    await client.query(`CREATE TABLE IF NOT EXISTS ${escapeIdentifier(model.dbName ?? model.name)} (${columns.join(", ")})`);
    for (const fields of [
      ...model.fields.filter(field => field.isUnique).map(field => [field.name]),
      ...model.uniqueFields,
    ]) {
      const index = `${model.dbName ?? model.name}_${fields.join("_")}_key`;
      await client.query(`CREATE UNIQUE INDEX IF NOT EXISTS ${escapeIdentifier(index)} ON ${escapeIdentifier(model.dbName ?? model.name)} (${fields.map(field => escapeIdentifier(model.fields.find(candidate => candidate.name === field)?.dbName ?? field)).join(", ")})`);
    }
  }
}